import { ArrowLeft, ArrowUpRight, BookOpen, CalendarBlank, CheckCircle, GitFork, GithubLogo, Star, Tag } from "@phosphor-icons/react";
import { MarkdownContent } from "../components/MarkdownContent.jsx";
import { formatCount, formatDate } from "../domain/catalog.js";

export function DetailView({ repo, repositories, onBack, onOpenRepo, onOpenCuration }) {
  if (!repo) return null;
  const related = (repo.relatedRepoIds || []).map((repoId) => repositories.find((item) => item.repoId === repoId)).filter(Boolean);
  return <main className="detail-page"><button className="back-link" type="button" onClick={onBack}><ArrowLeft size={17} /> 返回项目库</button>
    <header className="detail-cover"><div className="detail-identity"><img src={repo.avatar} alt="" /><div><p>{repo.categoryLabel} · {repo.resourceType}</p><h1>{repo.name}</h1><span>{repo.description}</span></div></div><div className="detail-actions"><a href={repo.url} target="_blank" rel="noreferrer"><GithubLogo size={19} /> GitHub <ArrowUpRight size={15} /></a>{repo.homepage && <a href={repo.homepage} target="_blank" rel="noreferrer">官方网站 <ArrowUpRight size={15} /></a>}{repo.contentLinks.map((link) => <a href={link.url} target="_blank" rel="noreferrer" key={link.url}>{link.label} <ArrowUpRight size={15} /></a>)}</div></header>
    <section className="fact-ribbon" aria-label="GitHub 仓库事实"><div><small>语言</small><strong>{repo.language}</strong></div><div><small>Stars</small><strong><Star weight="fill" size={18} />{formatCount(repo.stars)}</strong></div><div><small>Forks</small><strong><GitFork size={18} />{formatCount(repo.forks)}</strong></div><div><small>License</small><strong>{repo.license}</strong></div><div><small>上游状态</small><strong>{repo.archived ? "已归档" : "活跃"}</strong></div><div><small>收藏状态</small><strong>{repo.sourceStatus === "starred" ? "当前已 Star" : "已退出公开 Stars"}</strong></div></section>
    <div className="detail-editorial-grid"><article className="detail-story"><span className="detail-kicker">个人策展</span><section><h2>为什么收藏</h2><p>{repo.note || "尚未人工整理。此处只展示 GitHub 事实，不生成个人判断。"}</p></section><section><div className="note-heading"><h2>学习笔记</h2><button type="button" className="text-link" onClick={() => onOpenCuration(repo)}>{repo.contentMarkdown ? "编辑策展文件" : "整理此项目"}</button></div>{repo.contentMarkdown ? <MarkdownContent>{repo.contentMarkdown}</MarkdownContent> : <p>尚未留下学习笔记。</p>}</section><section><h2>个人标签</h2><div className="detail-tags">{repo.tags.length ? repo.tags.map((tag) => <span key={tag}><Tag size={14} />{tag}</span>) : <small>尚未添加个人标签</small>}</div></section><section><h2>GitHub Topics</h2><div className="detail-tags github-topics">{repo.topics.length ? repo.topics.slice(0, 12).map((topic) => <span key={topic}>{topic}</span>) : <small>上游未提供 Topics</small>}</div></section></article>
      <aside className="detail-record"><section><CalendarBlank size={20} /><span>收藏时间</span><strong>{formatDate(repo.starredAt)}</strong></section><section><CalendarBlank size={20} /><span>上游更新时间</span><strong>{formatDate(repo.pushedAt)}</strong></section><section><CheckCircle size={20} /><span>最近同步</span><strong>{formatDate(repo.lastSyncedAt)}</strong></section><section><CalendarBlank size={20} /><span>个人更新时间</span><strong>{repo.curatedAt ? formatDate(repo.curatedAt) : "尚未整理"}</strong></section><section><BookOpen size={20} /><span>学习阶段</span><strong>{repo.stageLabel}</strong></section><small>GitHub 事实与个人内容由独立文件维护。机器建议在 MVP 中为空。</small></aside>
      <aside className="related-feature"><span>RELATED / 人工关联</span>{related.length ? related.map((item) => <button type="button" key={item.repoId} onClick={() => onOpenRepo(item.repoId)}><img src={item.avatar} alt="" /><div><strong>{item.name}</strong><small>{item.note || item.description}</small></div><ArrowUpRight size={16} /></button>) : <p>尚未添加人工关联项目。</p>}</aside></div>
  </main>;
}
