import { useState } from "react";
import { ArrowRight, ArrowUpRight, Shuffle } from "@phosphor-icons/react";
import { formatDate } from "../domain/catalog.js";
import { chooseRevisit, collectionDate } from "../domain/filters.js";
export function HomeView({catalog,onOpenRepo,onOpenLibrary,onNavigate}) {
  const repos=catalog.repositories.filter(r=>r.sourceStatus==="starred"&&!r.personalArchived);
  const described=repos.filter(r=>r.hasGuide).sort((a,b)=>b.reviewedAt.localeCompare(a.reviewedAt)||new Date(b.starredAt)-new Date(a.starredAt)||a.repoId-b.repoId);
  const featured=described[0]||repos[0];
  const [revisit,setRevisit]=useState(()=>chooseRevisit(repos));
  const years=Object.entries(repos.reduce((acc,r)=>{const y=collectionDate(r.starredAt).slice(0,4);acc[y]=(acc[y]||0)+1;return acc;},{})).sort(([a],[b])=>b.localeCompare(a));
  if(!featured)return <main className="empty-state"><h1>暂时没有收藏</h1><p>下一次成功同步后，公开 Stars 会出现在这里。</p></main>;
  return <main className="home-page"><div className="home-magazine-grid">
    <section className="cover-intro"><p className="issue-label">你的 GitHub 收藏资料库</p><h1>回顾收藏<br/>找到所需</h1><div className="cover-stats"><span><strong>{catalog.stats.active}</strong>当前 Stars</span><span><strong>{catalog.stats.curated}</strong>已分类</span><span><strong>{catalog.stats.guides}</strong>仓库解读</span></div></section>
    <aside className="cover-manifesto"><p>想起一个用途，<br/>找回一个项目。</p><button className="text-link" type="button" onClick={()=>onOpenLibrary()}>浏览项目库 <ArrowRight size={17}/></button><small>最近成功检查 · {formatDate(catalog.checkedAt,{hour:"2-digit",minute:"2-digit"})}</small></aside>
    <aside className="home-category-rail"><div className="rail-heading"><h2>领域分类</h2><ArrowRight size={23}/></div><div className="rail-categories">{catalog.categories.filter(c=>c.id!=="unclassified").map(c=><button type="button" key={c.id} onClick={()=>onOpenLibrary({category:c.id})}><span>{c.label}</span><ArrowRight size={16}/></button>)}</div><div className="timeline-mini"><h3>按年份回顾</h3>{years.map(([year,count])=><button className="year-link" type="button" key={year} onClick={()=>onNavigate("history",{year,source:"all"})}><strong>{year}</strong><span>{count} 个当前收藏 <ArrowUpRight size={14}/></span></button>)}</div></aside>
    <article className="featured-copy"><span className="section-kicker">{featured.hasGuide?"最近补充解读":"最近收藏"}</span><h2>{featured.name}</h2><p>{featured.summary||featured.description}</p><div className="repo-meta-line"><span>{featured.categoryLabel}</span><span>{featured.resourceType}</span></div><button className="editor-note" type="button" onClick={()=>onOpenRepo(featured.repoId)}><span><strong>它能做什么，如何开始</strong>查看仓库介绍、使用方式与资料来源</span><ArrowUpRight size={19}/></button></article>
    <button className="featured-visual repository-portrait" type="button" aria-label={`查看 ${featured.name}`} onClick={()=>onOpenRepo(featured.repoId)}><img src={featured.avatar} alt=""/><span>{featured.owner}</span></button>
    <section className="current-interest"><div className="interest-title"><span>最近收藏</span><small>RECENT STARS</small></div>{repos.slice(0,3).map(repo=><button className="interest-story" type="button" key={repo.repoId} onClick={()=>onOpenRepo(repo.repoId)}><div className="interest-story-title"><img src={repo.avatar} alt=""/><div><h3>{repo.name}</h3><span>{repo.categoryLabel}</span></div></div><p>{repo.summary||repo.description}</p><time>{formatDate(repo.starredAt)}</time><span className="story-action">查看项目 <ArrowUpRight size={16}/></span></button>)}</section>
    <section className="home-action-strip"><div className="action-strip-title"><span>再次发现</span><small>FIND · READ · RETURN</small></div><button type="button" onClick={()=>onNavigate("history",{source:"all"})}><small>收藏回顾</small><strong>沿时间翻阅</strong><span>回到某一年，看看当时关注过什么</span><ArrowRight size={18}/></button><button type="button" onClick={()=>onOpenLibrary({coverage:"ready"})}><small>仓库解读</small><strong>{catalog.stats.guides} 篇介绍</strong><span>用途、使用步骤与有来源的示例</span><ArrowRight size={18}/></button><button type="button" onClick={()=>onOpenLibrary({origin:"new"})}><small>建库后新收藏</small><strong>{catalog.stats.new} 个项目</strong><span>最近加入资料库的仓库</span><ArrowRight size={18}/></button><div className="revisit-action"><small>随机重访旧收藏</small>{revisit&&<button type="button" onClick={()=>onOpenRepo(revisit.repoId)}><strong>{revisit.name}</strong><span>{revisit.summary||revisit.description}</span></button>}<button type="button" className="shuffle-button" onClick={()=>setRevisit(chooseRevisit(repos,Math.random,revisit?.repoId))}><Shuffle size={18}/>换一个</button></div></section>
  </div></main>;
}
