import { ArrowRight, BookOpen, CheckCircle, Play, Queue, Sparkle } from "@phosphor-icons/react";

function LearningRow({ repo, action, onAction, onOpenRepo }) {
  return <article className="learning-row"><button className="learning-main" type="button" onClick={() => onOpenRepo(repo.repoId)}><img src={repo.avatar} alt="" /><span><small>{repo.categoryLabel}</small><strong>{repo.name}</strong><p>{repo.takeaway || repo.note || repo.description}</p></span><ArrowRight size={18} /></button>{action && <button className="row-action" type="button" onClick={() => onAction(repo)}>{action}</button>}</article>;
}

export function LearningView({ catalog, onOpenRepo, onOpenLibrary, onOpenCuration }) {
  const active = catalog.repositories.filter((repo) => repo.sourceStatus === "starred" && !repo.personalArchived);
  const groups = Object.fromEntries(["learning", "queued", "learned", "imported", "reference"].map((stage) => [stage, active.filter((repo) => repo.stage === stage)]));
  return <main className="workspace-page learning-page"><header className="workspace-hero"><div><p>学习工作台 · Git 版本化记录</p><h1>让收藏产生结果</h1></div><div className="learning-score"><span>已人工整理</span><strong>{catalog.stats.curated}</strong><small>共 {catalog.stats.active} 个当前 Stars</small></div></header>
    <section className="learning-focus"><div className="focus-label"><Play weight="fill" size={18} /> CURRENT</div>{groups.learning.length ? groups.learning.map((repo) => <div className="focus-card" key={repo.repoId}><img src={repo.avatar} alt="" /><div><small>正在学习</small><h2>{repo.name}</h2><p>{repo.note}</p><blockquote>{repo.takeaway}</blockquote></div><button type="button" onClick={() => onOpenRepo(repo.repoId)}><BookOpen size={18} /> 查看学习记录</button></div>) : <div className="focus-card empty"><p>当前没有学习中的项目，可从待学习列表选择下一项。</p></div>}</section>
    <div className="learning-columns"><section><header><Queue size={20} /><div><h2>待学习</h2><span>{groups.queued.length} 个项目</span></div></header>{groups.queued.slice(0, 8).map((repo) => <LearningRow repo={repo} key={repo.repoId} action="查看详情" onOpenRepo={onOpenRepo} onAction={(item) => onOpenRepo(item.repoId)} />)}</section><section><header><CheckCircle size={20} /><div><h2>最近已学习</h2><span>{groups.learned.length} 条结论</span></div></header>{groups.learned.slice(0, 8).map((repo) => <LearningRow repo={repo} key={repo.repoId} onOpenRepo={onOpenRepo} />)}</section><section><header><BookOpen size={20} /><div><h2>历史待整理</h2><span>{groups.imported.length} 个项目</span></div></header>{groups.imported.slice(0, 5).map((repo) => <LearningRow repo={repo} key={repo.repoId} action="去整理" onOpenRepo={onOpenRepo} onAction={onOpenCuration} />)}<button className="section-footer-link" type="button" onClick={() => onOpenLibrary({ stage: "imported" })}><Sparkle size={16} /> 查看全部 {groups.imported.length} 个历史项目</button><button className="section-footer-link" type="button" onClick={() => onOpenLibrary({ stage: "reference" })}>查看 {groups.reference.length} 个仅参考项目</button></section></div>
  </main>;
}
